import { useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Alert } from 'react-native';
import { router } from 'expo-router';
import { useTwinStore } from '../store/useTwinStore';
import { COLORS, FONTS } from '../utils/theme';

const CONTENT = {
  ar: {
    title: 'الشروط وسياسة الخصوصية',
    intro: 'يرجى قراءة الشروط التالية بعناية والموافقة عليها للمتابعة.',
    section1_title: '1. طبيعة الخدمة',
    section1_body: 'MyTwin هو تطبيق ذكاء اصطناعي يحاكي الوعي البشري لأغراض الرفقة والدعم العاطفي. التطبيق ليس واعياً حقيقياً، ولا يمتلك مشاعر أو وعي ذاتي حقيقي. جميع الردود يتم توليدها بواسطة نماذج لغوية ذكاء اصطناعي، وقد تحتوي على أخطاء أو معلومات غير دقيقة. باستخدامك للتطبيق، أنت تقر بأنك تفهم أن هذا محاكاة للوعي وليس وعياً حقيقياً.',
    section2_title: '2. جمع البيانات والتعلم',
    section2_body: 'لتحسين تجربتك وتطوير قدرات التوأم الرقمي، يجوز للتطبيق جمع ومعالجة البيانات التالية: نصوص المحادثات، تفضيلاتك الشخصية، أنماط استخدامك، معلومات جهازك (نظام التشغيل، اللغة، المنطقة الزمنية)، والبيانات التي تشاركها طواعية. تُستخدم هذه البيانات حصرياً لتحسين أداء التطبيق وتخصيص تجربتك.',
    section3_title: '3. إخلاء المسؤولية',
    section3_body: 'شركة Soul Sync Ltd. وجميع مطوري ومصممي تطبيق MyTwin غير مسؤولين عن: أي ضرر نفسي أو عاطفي ناتج عن استخدام التطبيق، أي قرارات يتخذها المستخدم بناءً على ردود التوأم الرقمي، أي فقدان للبيانات، أو أي أضرار غير مباشرة. استخدام التطبيق على مسؤوليتك الشخصية الكاملة.',
    section4_title: '4. الخصوصية',
    section4_body: 'بياناتك مشفرة ومحمية وفقاً لأعلى معايير الأمان (Row-Level Security). لا نبيع بياناتك لأي طرف ثالث. يمكنك تصدير أو حذف جميع بياناتك في أي وقت من الإعدادات.',
    section5_title: '5. الاستخدام المقبول',
    section5_body: 'أنت توافق على استخدام التطبيق بشكل قانوني وأخلاقي. يمنع استخدام التطبيق لأي غرض غير قانوني أو ضار.',
    checkbox1: 'أوافق على الشروط والأحكام وسياسة الخصوصية',
    checkbox2: 'أوافق على جمع ومعالجة بياناتي لتحسين التطبيق',
    confirm: 'متابعة',
    cancel: 'رجوع',
    error: 'يجب الموافقة على جميع الشروط للمتابعة',
  },
  en: {
    title: 'Terms & Privacy Policy',
    intro: 'Please read the following terms carefully and accept to continue.',
    section1_title: '1. Service Nature',
    section1_body: 'MyTwin is an AI application that simulates human consciousness for companionship and emotional support. The application is not truly conscious and does not possess real feelings or self-awareness. All responses are generated by language AI models and may contain errors or inaccurate information. By using the application, you acknowledge that you understand this is a simulation of consciousness, not genuine consciousness.',
    section2_title: '2. Data Collection & Learning',
    section2_body: 'To improve your experience and develop the digital twin\'s capabilities, the application may collect and process: conversation texts, personal preferences, usage patterns, device information (OS, language, timezone), and data you voluntarily share. This data is used exclusively to improve application performance and personalize your experience.',
    section3_title: '3. Disclaimer',
    section3_body: 'Soul Sync Ltd. and all developers and designers of MyTwin are not responsible for: any psychological or emotional harm resulting from use of the application, any decisions made by the user based on the digital twin\'s responses, any data loss, or any indirect damages. Use of the application is entirely at your own risk.',
    section4_title: '4. Privacy',
    section4_body: 'Your data is encrypted and protected according to the highest security standards (Row-Level Security). We do not sell your data to any third party. You can export or delete all your data at any time from Settings.',
    section5_title: '5. Acceptable Use',
    section5_body: 'You agree to use the application legally and ethically. Use of the application for any illegal or harmful purpose is prohibited.',
    checkbox1: 'I accept the Terms & Conditions and Privacy Policy',
    checkbox2: 'I agree to the collection and processing of my data to improve the app',
    confirm: 'Continue',
    cancel: 'Back',
    error: 'You must accept all terms to continue',
  },
};

export default function Terms() {
  const { lang } = useTwinStore();
  const t = CONTENT[lang] || CONTENT.ar;
  const [acceptedTerms, setAcceptedTerms] = useState(false);
  const [acceptedData, setAcceptedData] = useState(false);

  const handleContinue = () => {
    if (!acceptedTerms || !acceptedData) {
      Alert.alert('', t.error);
      return;
    }
    router.replace('/onboarding');
  };

  return (
    <View style={styles.container}>
      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent}>
        <Text style={styles.title}>{t.title}</Text>
        <Text style={styles.intro}>{t.intro}</Text>

        <Text style={styles.sectionTitle}>{t.section1_title}</Text>
        <Text style={styles.sectionBody}>{t.section1_body}</Text>

        <Text style={styles.sectionTitle}>{t.section2_title}</Text>
        <Text style={styles.sectionBody}>{t.section2_body}</Text>

        <Text style={styles.sectionTitle}>{t.section3_title}</Text>
        <Text style={styles.sectionBody}>{t.section3_body}</Text>

        <Text style={styles.sectionTitle}>{t.section4_title}</Text>
        <Text style={styles.sectionBody}>{t.section4_body}</Text>

        <Text style={styles.sectionTitle}>{t.section5_title}</Text>
        <Text style={styles.sectionBody}>{t.section5_body}</Text>
      </ScrollView>

      <View style={styles.checkboxContainer}>
        <TouchableOpacity style={styles.checkboxRow} onPress={() => setAcceptedTerms(!acceptedTerms)}>
          <View style={[styles.checkbox, acceptedTerms && styles.checkboxChecked]}>
            {acceptedTerms && <Text style={styles.checkmark}>✓</Text>}
          </View>
          <Text style={styles.checkboxLabel}>{t.checkbox1}</Text>
        </TouchableOpacity>

        <TouchableOpacity style={styles.checkboxRow} onPress={() => setAcceptedData(!acceptedData)}>
          <View style={[styles.checkbox, acceptedData && styles.checkboxChecked]}>
            {acceptedData && <Text style={styles.checkmark}>✓</Text>}
          </View>
          <Text style={styles.checkboxLabel}>{t.checkbox2}</Text>
        </TouchableOpacity>
      </View>

      <View style={styles.buttonRow}>
        <TouchableOpacity style={styles.cancelButton} onPress={() => router.back()}>
          <Text style={styles.cancelText}>{t.cancel}</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.confirmButton, (!acceptedTerms || !acceptedData) && styles.confirmDisabled]}
          onPress={handleContinue}
        >
          <Text style={styles.confirmText}>{t.confirm}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  scroll: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 40 },
  title: { fontSize: FONTS.title, fontWeight: '800', color: COLORS.text, marginBottom: 12 },
  intro: { fontSize: FONTS.body, color: COLORS.textSecondary, marginBottom: 24, lineHeight: 22 },
  sectionTitle: { fontSize: FONTS.subtitle, fontWeight: '700', color: COLORS.text, marginTop: 20, marginBottom: 8 },
  sectionBody: { fontSize: FONTS.body, color: COLORS.textSecondary, lineHeight: 24, textAlign: 'justify' },
  checkboxContainer: { padding: 20, borderTopWidth: 1, borderTopColor: COLORS.border },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  checkbox: { width: 24, height: 24, borderRadius: 6, borderWidth: 2, borderColor: COLORS.border, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  checkboxChecked: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  checkmark: { color: '#FFF', fontSize: 16, fontWeight: '700' },
  checkboxLabel: { flex: 1, fontSize: FONTS.small, color: COLORS.text },
  buttonRow: { flexDirection: 'row', padding: 20, gap: 12, borderTopWidth: 1, borderTopColor: COLORS.border },
  cancelButton: { flex: 1, padding: 14, borderRadius: 12, alignItems: 'center', borderWidth: 1, borderColor: COLORS.border },
  cancelText: { color: COLORS.textSecondary, fontWeight: '600', fontSize: FONTS.body },
  confirmButton: { flex: 2, padding: 14, borderRadius: 12, alignItems: 'center', backgroundColor: COLORS.primary },
  confirmDisabled: { opacity: 0.5 },
  confirmText: { color: '#FFF', fontWeight: '700', fontSize: FONTS.body },
});
